"""Determinism test for ``scripts/recalibrate_thresholds.py``.

The recalibrate script is deterministic on identical input by design — a
stable file ordering, fresh collector instances per session, inclusive
ventiles, and fixed-precision float formatting all fall out of the same
property the script promises in its module docstring. This test pins the
output against a golden string so any future regression in determinism
fails loudly under CI.

The golden snapshot embeds inline rather than living in a sidecar file
so a contributor regenerating the corpus only has to touch one place.
"""

from __future__ import annotations

import pytest

from scripts.recalibrate_thresholds import main as recalibrate_main

EXPECTED_OUTPUT: str = """\
# codevigil threshold calibration
# Generated by scripts/recalibrate_thresholds.py
# warn_threshold = p80, critical_threshold = p95

[collectors.read_edit_ratio]
# derived from 5 session(s)
warn_threshold = 7.2000
critical_threshold = 7.8000

[collectors.reasoning_loop]
# derived from 5 session(s)
warn_threshold = 0.0000
critical_threshold = 0.0000

[collectors.stop_phrase]
# derived from 5 session(s)
warn_threshold = 0.2000
critical_threshold = 0.8000
"""


def test_recalibrate_emits_deterministic_output(capsys: pytest.CaptureFixture[str]) -> None:
    exit_code = recalibrate_main(["--fixtures-dir", "tests/fixtures/sessions"])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert captured.out == EXPECTED_OUTPUT
