#!/usr/bin/env python3
"""Emit suggested collector thresholds from a fixture corpus.

Walks a directory of ``*.jsonl`` Claude Code session fixtures, runs the
three v0.1 user-facing collectors (``read_edit_ratio``, ``stop_phrase``,
``reasoning_loop``) against each, captures the final snapshot per
collector per session, and prints a TOML snippet that users can paste
into ``~/.config/codevigil/config.toml`` to replace the built-in
experimental thresholds with values calibrated against their own data.

Output is deterministic: sessions are sorted by filename, collectors
are instantiated fresh per session, quantiles use inclusive ventiles,
and floats are formatted with a fixed precision so rerunning the
script against the same corpus produces byte-identical output. That
property makes the script testable and diffable under git.

Usage::

    scripts/recalibrate_thresholds.py [--fixtures-dir tests/fixtures/sessions]

The default path lines up with the fixture corpus landing in a later
phase; for this phase the script accepts any directory containing
``.jsonl`` fixtures so it can be exercised in isolation.
"""

from __future__ import annotations

import argparse
import io
import statistics
import sys
from pathlib import Path
from typing import Any

from codevigil.collectors.read_edit_ratio import ReadEditRatioCollector
from codevigil.collectors.reasoning_loop import ReasoningLoopCollector
from codevigil.collectors.stop_phrase import StopPhraseCollector
from codevigil.parser import SessionParser
from codevigil.types import MetricSnapshot

_DEFAULT_FIXTURES_DIR: Path = Path("tests/fixtures/sessions")

_COLLECTOR_FACTORIES: dict[str, Any] = {
    "read_edit_ratio": ReadEditRatioCollector,
    "stop_phrase": StopPhraseCollector,
    "reasoning_loop": ReasoningLoopCollector,
}


def _collect_snapshots(fixtures_dir: Path) -> dict[str, list[float]]:
    """Return the per-collector final-value distribution across fixtures."""

    distributions: dict[str, list[float]] = {name: [] for name in _COLLECTOR_FACTORIES}
    files = sorted(p for p in fixtures_dir.glob("*.jsonl") if p.is_file())
    for path in files:
        parser = SessionParser(session_id=path.stem)
        instances = {name: factory() for name, factory in _COLLECTOR_FACTORIES.items()}
        try:
            with path.open("r", encoding="utf-8", errors="replace") as handle:
                for event in parser.parse(handle):
                    for collector in instances.values():
                        try:
                            collector.ingest(event)
                        except Exception:
                            continue
        except OSError:
            continue
        for name, collector in instances.items():
            try:
                snap: MetricSnapshot = collector.snapshot()
            except Exception:
                continue
            distributions[name].append(float(snap.value))
    return distributions


def _quantiles(values: list[float]) -> tuple[float, float]:
    if not values:
        return (0.0, 0.0)
    if len(values) == 1:
        only = float(values[0])
        return (only, only)
    ventiles = statistics.quantiles(values, n=20, method="inclusive")
    return (float(ventiles[15]), float(ventiles[18]))


def _format_toml(distributions: dict[str, list[float]]) -> str:
    """Emit a deterministic TOML snippet with the derived thresholds.

    Each section is headed by a comment describing the quantiles and the
    sample count so users can judge whether the suggestion is trustworthy.
    Floats are formatted with four decimal places — enough resolution for
    hit-rate and ratio metrics, tight enough that test output stays stable.
    """

    buf = io.StringIO()
    buf.write("# codevigil threshold calibration\n")
    buf.write("# Generated by scripts/recalibrate_thresholds.py\n")
    buf.write("# warn_threshold = p80, critical_threshold = p95\n")
    for name in sorted(distributions):
        values = distributions[name]
        warn, critical = _quantiles(values)
        buf.write("\n")
        buf.write(f"[collectors.{name}]\n")
        buf.write(f"# derived from {len(values)} session(s)\n")
        buf.write(f"warn_threshold = {warn:.4f}\n")
        buf.write(f"critical_threshold = {critical:.4f}\n")
    return buf.getvalue()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="recalibrate_thresholds",
        description="Emit calibrated threshold suggestions from a fixture corpus.",
    )
    parser.add_argument(
        "--fixtures-dir",
        type=Path,
        default=_DEFAULT_FIXTURES_DIR,
        help="Directory containing *.jsonl session fixtures.",
    )
    args = parser.parse_args(argv)

    fixtures_dir: Path = args.fixtures_dir
    if not fixtures_dir.is_dir():
        sys.stderr.write(f"error: fixtures directory {fixtures_dir!s} does not exist\n")
        return 2
    distributions = _collect_snapshots(fixtures_dir)
    sys.stdout.write(_format_toml(distributions))
    return 0


if __name__ == "__main__":  # pragma: no cover - script entry
    raise SystemExit(main())
